<?php
declare(strict_types=1);
if (PHP_SAPI !== 'cli') exit;
require dirname(__DIR__) . '/vendor/autoload.php';
date_default_timezone_set('America/Bogota');
$root = dirname(__DIR__);
$config = array_replace(require $root . '/config/default.php', require $root . '/config/local.php');
$databaseName = 'citaya_test_' . bin2hex(random_bytes(5));
$server = new PDO(preg_replace('/;dbname=[^;]+/', '', $config['db_dsn']), $config['db_user'], $config['db_password'], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
$server->exec("CREATE DATABASE `$databaseName` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
$config['db_dsn'] = preg_replace('/dbname=[^;]+/', 'dbname=' . $databaseName, $config['db_dsn']);
$config['storage_path'] = $root . '/.runtime/' . $databaseName;
$config['mail_transport'] = 'local';
$config['smtp_host'] = '127.0.0.1';
$config['smtp_port'] = 1;
$config['smtp_user'] = 'test';
$config['smtp_password'] = 'test';
mkdir($config['storage_path'] . '/histories', 0700, true);
mkdir($config['storage_path'] . '/outbox', 0700, true);
$db = new App\Database($config);
$app = new App\Application($db, $config);
$worker = new App\MailWorker($app);
$checks = 0;
function check(bool $condition, string $label): void { global $checks; if (!$condition) throw new RuntimeException('FAIL: ' . $label); $checks++; echo "OK $label\n"; }
function rejects(callable $fn, string $label): void { try { $fn(); } catch (DomainException) { check(true, $label); return; } check(false, $label); }
function freshRequest(?string $document = null): array {
    global $db, $app;
    $number = $document ?? (string) random_int(2000000000, 2999999999);
    if (!$db->one('SELECT id FROM patients WHERE document_number=?', [$number])) $db->insert('patients', ['document_type'=>'CC','document_number'=>$number,'full_name'=>'Paciente de prueba','email'=>$app->config['test_recipient'],'email_verified_at'=>$app->now()]);
    $id = $app->createRequest(['document_type'=>'CC','document_number'=>$number,'full_name'=>'Paciente de prueba','approximate_date'=>date('Y-m-d'),'specialty_id'=>0,'email'=>$app->config['test_recipient']], 'test-' . bin2hex(random_bytes(4)));
    $job = $db->one("SELECT * FROM jobs WHERE request_id=? AND kind='otp'", [$id]);
    return [$id, App\Crypto::open($job['encrypted_payload'], $app->config['app_key'])];
}
function verifiedRequest(): int { global $app; [$id,$code]=freshRequest(); check($app->verify($id,$code,'verify-'. $id), 'Código válido autoriza solicitud ' . $id); return $id; }
function addEncounter(int $patientId, int $days = 0, int $specialtyId = 1): array {
    global $db,$app;
    $encounterId=$db->insert('encounters',['patient_id'=>$patientId,'specialty_id'=>$specialtyId,'attended_at'=>date('Y-m-d 08:00:00',strtotime("$days days")),'admission'=>bin2hex(random_bytes(6)),'location'=>'Sede de prueba']);
    $packageId=$db->insert('packages',['encounter_id'=>$encounterId,'version'=>1,'status'=>'available','published_at'=>$app->now()]);
    $paths=[];
    foreach ([1,2] as $index) {
        $name=bin2hex(random_bytes(16)).'.pdf'; $path=$app->config['storage_path'].'/histories/'.$name;
        file_put_contents($path,"%PDF-1.4\nPDF ficticio de prueba $index\n%%EOF");
        $db->insert('clinical_files',['package_id'=>$packageId,'storage_name'=>$name,'original_name'=>'test.pdf','sort_order'=>$index,'size_bytes'=>filesize($path),'sha256'=>hash_file('sha256',$path)]);
        $paths[]=$path;
    }
    return [$encounterId,$packageId,$paths];
}
try {
    $db->pdo->exec(file_get_contents($root . '/database/schema.sql'));
    $db->insert('specialties',['name'=>'Ortopedia']); $db->insert('specialties',['name'=>'Alergología']);
    rejects(fn()=>$app->filters(['approximate_date'=>'2026-02-30']), 'Rechaza fecha inexistente');
    rejects(fn()=>$app->filters(['approximate_date'=>date('Y-m-d',strtotime('+1 day'))]), 'Rechaza fecha futura');
    rejects(fn()=>$app->identity(['document_type'=>'CC','document_number'=>'ABC']), 'Valida identificación numérica');
    check($app->identity(['document_type'=>'CC','document_number'=>'001234'])[1]==='001234','Conserva ceros iniciales');
    [$id,$code]=freshRequest();
    check($app->request($id)['contact_email']===$config['test_recipient'],'Conserva correo declarado en la solicitud');
    check($db->one("SELECT recipient FROM jobs WHERE request_id=? AND kind='otp'",[$id])['recipient']===$config['test_recipient'],'Usa el correo declarado para la verificación');
    rejects(fn()=>$app->createRequest(['document_type'=>'CC','document_number'=>'1000000001','full_name'=>'Paciente de prueba','approximate_date'=>date('Y-m-d'),'specialty_id'=>0,'email'=>'correo-invalido'],'invalid-email'),'Rechaza correo inválido en el servidor');
    rejects(fn()=>$app->search($id),'Bloquea búsqueda sin verificar');
    check(!$app->verify($id,'000000','otp-invalid'),'Rechaza código incorrecto');
    check($app->verify($id,$code,'otp-valid'),'Acepta código correcto');
    check(!$app->verify($id,$code,'otp-replay'),'Rechaza reutilización');
    $patientId=(int)$app->request($id)['patient_id'];
    [$encounterId,$packageId,$paths]=addEncounter($patientId,-2);
    addEncounter($patientId,-10,2); addEncounter($patientId,-31); addEncounter($patientId,1);
    check(count($app->search($id))===2,'Busca por paciente y rango, excluye futuro y fuera de rango');
    $app->changeFilters($id,['approximate_date'=>date('Y-m-d'),'specialty_id'=>2]);
    check(count($app->search($id))===1,'Filtra por especialidad');
    $app->changeFilters($id,['approximate_date'=>date('Y-m-d'),'specialty_id'=>0]);
    $other=verifiedRequest(); [$otherEncounter]=addEncounter((int)$app->request($other)['patient_id']);
    rejects(fn()=>$app->confirm($id,$otherEncounter),'Impide seleccionar atención de otro paciente');
    $app->confirm($id,$encounterId); $app->confirm($id,$encounterId);
    check((int)$db->one("SELECT COUNT(*) n FROM jobs WHERE request_id=? AND kind='history'",[$id])['n']===1,'Confirmación repetida crea una sola entrega');
    while ($worker->tick()) {}
    check($app->request($id)['status']==='simulated','Entrega local completa');
    $mailJob=$db->one("SELECT * FROM jobs WHERE request_id=? AND kind='history'",[$id]);
    $mime=file_get_contents($config['storage_path'].'/outbox/'.$mailJob['id'].'.eml');
    check(substr_count($mime,'Content-Disposition: attachment;')===2,'Incluye los dos PDF sin omitir anexos');
    check(str_contains($mime,base64_encode(file_get_contents($paths[0]))),'Conserva bytes del PDF original en MIME');
    [$expired,$expiredCode]=freshRequest();
    $db->run('UPDATE verifications SET expires_at=? WHERE request_id=?',[date('Y-m-d H:i:s',time()-1),$expired]);
    check(!$app->verify($expired,$expiredCode,'expired'),'Código vencido no autoriza');
    [$limited,$limitedCode]=freshRequest();
    for($i=0;$i<5;$i++) $app->verify($limited,'000000','limited');
    check(!$app->verify($limited,$limitedCode,'limited'),'Límite de cinco intentos');
    [$resend,$oldCode]=freshRequest();
    rejects(fn()=>$app->resend($resend,'resend'),'Respeta espera de reenvío');
    $db->run('UPDATE verifications SET created_at=? WHERE request_id=?',[date('Y-m-d H:i:s',time()-70),$resend]);
    $app->resend($resend,'resend');
    $oldJob=$db->one("SELECT * FROM jobs WHERE request_id=? ORDER BY id LIMIT 1",[$resend]);
    check($oldJob['status']==='cancelled' && $oldJob['encrypted_payload']===null,'Invalida correo antiguo y borra código pendiente');
    $db->run("UPDATE jobs SET status='cancelled',encrypted_payload=NULL WHERE kind='otp' AND status IN ('queued','retry')");
    $missing=verifiedRequest(); [$missingEncounter,$missingPackage,$missingPaths]=addEncounter((int)$app->request($missing)['patient_id']);
    file_put_contents($missingPaths[0],'tampered');
    $app->confirm($missing,$missingEncounter);
    check($app->request($missing)['status']==='unavailable','No entrega paquetes alterados');
    $missingFile=verifiedRequest(); [$missingFileEncounter,,$missingFilePaths]=addEncounter((int)$app->request($missingFile)['patient_id']);
    unlink($missingFilePaths[1]); $app->confirm($missingFile,$missingFileEncounter);
    check($app->request($missingFile)['status']==='unavailable','No entrega paquete con archivo faltante');
    $changed=verifiedRequest(); [$changedEncounter]=addEncounter((int)$app->request($changed)['patient_id']);
    $app->confirm($changed,$changedEncounter);
    $db->run("UPDATE patients SET email='changed@example.test' WHERE id=?",[$app->request($changed)['patient_id']]);
    $externalConfig=$config; $externalConfig['mail_transport']='smtp';
    $externalWorker=new App\MailWorker(new App\Application($db,$externalConfig));
    while($externalWorker->tick()){}
    check($app->request($changed)['status']==='failed','Correo cambiado bloquea envío externo ya en cola');
    $withdrawn=verifiedRequest(); [$withdrawnEncounter,$withdrawnPackage]=addEncounter((int)$app->request($withdrawn)['patient_id']);
    $app->confirm($withdrawn,$withdrawnEncounter); $db->run("UPDATE packages SET status='withdrawn' WHERE id=?",[$withdrawnPackage]);
    while($worker->tick()){}
    check($app->request($withdrawn)['status']==='failed','Retiro posterior al encolado bloquea entrega');
    $smallConfig=$config; $smallConfig['max_mail_bytes']=100;
    rejects(fn()=>(new App\Application($db,$smallConfig))->packageFiles($packageId),'Bloquea paquetes superiores al límite');
    $stale=verifiedRequest(); [$staleEncounter]=addEncounter((int)$app->request($stale)['patient_id']); $app->confirm($stale,$staleEncounter);
    $db->run("UPDATE jobs SET status='sending',locked_at=? WHERE request_id=? AND kind='history'",[date('Y-m-d H:i:s',time()-400),$stale]);
    while($worker->tick()){}
    check($app->request($stale)['status']==='uncertain','No reenvía un trabajo abandonado con resultado incierto');
    $app->limit('one',1,60); rejects(fn()=>$app->limit('one',1,60),'Limitador de solicitudes persiste los intentos');
    $unknown=$app->createRequest(['document_type'=>'CC','document_number'=>'9999999999','full_name'=>'Paciente no registrado','approximate_date'=>date('Y-m-d'),'specialty_id'=>0,'email'=>'contacto@example.test'],'unknown');
    check($app->request($unknown)['patient_id']===null,'Solicitud desconocida obtiene radicado sin revelar existencia');
    check((int)$db->one('SELECT COUNT(*) n FROM jobs WHERE request_id=?',[$unknown])['n']===0,'No envía correo para paciente desconocido');
    check(!$app->verify($unknown,'000000','unknown'),'Paciente desconocido no obtiene acceso');
    check(App\Crypto::open(App\Crypto::seal('secret',$config['app_key']),$config['app_key'])==='secret','Cifrado autenticado de códigos en cola');
    $smtpRequest=verifiedRequest(); [$smtpEncounter]=addEncounter((int)$app->request($smtpRequest)['patient_id']); $app->confirm($smtpRequest,$smtpEncounter);
    $db->run("UPDATE jobs SET status='cancelled',encrypted_payload=NULL WHERE kind='otp' AND status IN ('queued','retry')");
    $smtpConfig=$config; $smtpConfig['mail_transport']='smtp'; $smtpConfig['smtp_host']='127.0.0.1'; $smtpConfig['smtp_port']=1; $smtpConfig['smtp_user']='test'; $smtpConfig['smtp_password']='test';
    $smtpWorker=new App\MailWorker(new App\Application($db,$smtpConfig));
    $smtpWorker->tick();
    check($app->request($smtpRequest)['status']==='retry','Fallo de conexión SMTP programa reintento');
    for($attempt=0;$attempt<2;$attempt++) { $db->run('UPDATE jobs SET available_at=? WHERE request_id=?',[date('Y-m-d H:i:s',time()-1),$smtpRequest]); $smtpWorker->tick(); }
    check($app->request($smtpRequest)['status']==='failed','SMTP deja de reintentar después de tres intentos');
    require __DIR__.'/TestPdf.php';
    $importSource=$config['storage_path'].'/histories/import-fixture.pdf';
    file_put_contents($importSource,testPdf('6000000011','AUTOINDEX123','IMPORTACION'));
    $importedPackage=(new App\Repository($app))->importPackage([['path'=>$importSource,'name'=>'historia.pdf']]);
    $indexed=$db->one("SELECT * FROM patients WHERE document_number='6000000011'");
    check($indexed!==null && $indexed['email_verified_at']===null,'Importa paciente desde PDF sin registro ni correo previo');
    $importedEncounter=$db->one('SELECT e.* FROM encounters e JOIN packages p ON p.encounter_id=e.id WHERE p.id=?',[$importedPackage]);
    $indexedRequest=$app->createRequest(['document_type'=>'CC','document_number'=>'6000000011','full_name'=>$indexed['full_name'],'approximate_date'=>date('Y-m-d'),'specialty_id'=>$importedEncounter['specialty_id'],'email'=>'solicitante@example.test'],'indexed-pdf');
    $codeJob=$db->one("SELECT * FROM jobs WHERE request_id=? AND kind='otp'",[$indexedRequest]);
    check($codeJob['recipient']==='solicitante@example.test','La simulación usa el correo escrito en el formulario');
    check($app->verify($indexedRequest,App\Crypto::open($codeJob['encrypted_payload'],$config['app_key']),'indexed-pdf'),'Verifica solicitud del paciente detectado automáticamente');
    $app->confirm($indexedRequest,(int)$importedEncounter['id']);
    while($worker->tick()){}
    check($app->request($indexedRequest)['status']==='simulated','Entrega local del PDF indexado sin registrar manualmente al paciente');
    check(!(new App\Application($db,$smtpConfig))->canUseRecipient($indexed,'solicitante@example.test'),'El flujo histórico conserva su comprobación de destinatario');
    $directData=['document_type'=>'CC','document_number'=>'6000000011','full_name'=>$indexed['full_name'],'approximate_date'=>date('Y-m-d'),'specialty_id'=>$importedEncounter['specialty_id'],'email'=>'buscador@example.test'];
    $direct=$app->createRequest($directData,'direct-search',true);
    check($app->request($direct)['status']==='queued','Una coincidencia prepara automáticamente la entrega al enviar el formulario');
    check((int)$db->one("SELECT COUNT(*) n FROM jobs WHERE request_id=? AND kind='otp'",[$direct])['n']===0,'Búsqueda directa no genera códigos');
    check($app->request($direct)['verified_at']===null && $app->request($direct)['verified_email']===null,'Coincidencia no se registra como identidad ni correo verificado');
    $app->processSearch($direct);
    check((int)$db->one("SELECT COUNT(*) n FROM jobs WHERE request_id=? AND kind='history'",[$direct])['n']===1,'Procesar de nuevo la misma búsqueda no duplica el envío');
    while($worker->tick()){}
    check($app->request($direct)['status']==='simulated','La búsqueda directa entrega el paquete en correo local al destinatario escrito');
    $mismatch=$app->createRequest(array_replace($directData,['full_name'=>'Nombre de otra persona']),'name-mismatch',true);
    check($app->request($mismatch)['status']==='no_matches' && (int)$db->one('SELECT COUNT(*) n FROM jobs WHERE request_id=?',[$mismatch])['n']===0,'Nombre diferente impide coincidencia y envío');
    $wrongDate=$app->createRequest(array_replace($directData,['approximate_date'=>date('Y-m-d',strtotime('-100 days'))]),'date-mismatch',true);
    check($app->request($wrongDate)['status']==='no_matches','Fecha fuera del rango no envía otra atención');
    addEncounter((int)$indexed['id'],0,(int)$importedEncounter['specialty_id']);
    $ambiguous=$app->createRequest($directData,'ambiguous-search',true);
    check($app->request($ambiguous)['status']==='awaiting_selection' && (int)$db->one('SELECT COUNT(*) n FROM jobs WHERE request_id=?',[$ambiguous])['n']===0,'Varias atenciones requieren selección y no envían todas indiscriminadamente');
    $directSmtpApp=new App\Application($db,$smtpConfig);
    check($directSmtpApp->canUseRecipient($indexed,'otro@example.test',true),'SMTP directo acepta correo declarado sin autorización previa');
    check(!$directSmtpApp->canUseRecipient($indexed,'invalido',true),'SMTP directo rechaza correo inválido');
    check(!$directSmtpApp->canUseRecipient(array_replace($indexed,['active'=>0]),'otro@example.test',true),'SMTP directo respeta paciente desactivado');
    $smtpPatient=$db->insert('patients',['document_type'=>'CC','document_number'=>'6000000022','full_name'=>'Paciente SMTP','email'=>'','email_verified_at'=>null]);
    addEncounter($smtpPatient);
    $smtpData=['document_type'=>'CC','document_number'=>'6000000022','full_name'=>'Paciente SMTP','approximate_date'=>date('Y-m-d'),'specialty_id'=>1,'email'=>'destino-libre@example.test'];
    $smtpDirect=$directSmtpApp->createRequest($smtpData,'smtp-direct',true);
    check($directSmtpApp->request($smtpDirect)['status']==='queued','SMTP encola automáticamente para destinatario fuera de test_recipient');
    $directSmtpWorker=new App\MailWorker($directSmtpApp);
    $directSmtpWorker->tick();
    $smtpDirectJob=$db->one("SELECT * FROM jobs WHERE request_id=? AND kind='history'",[$smtpDirect]);
    check($smtpDirectJob['status']==='retry' && str_starts_with($smtpDirectJob['last_error'],'transport_error_'),'Destinatario declarado alcanza el transporte SMTP sin bloqueo de autorización');
    check($smtpDirectJob['recipient']==='destino-libre@example.test' && $directSmtpApp->request($smtpDirect)['verified_email']===null,'Conserva destino solicitado sin inventar verificación');
    $db->run("UPDATE jobs SET status='cancelled' WHERE request_id=?",[$smtpDirect]);
    $tampered=$directSmtpApp->createRequest($smtpData,'smtp-tampered',true);
    $db->run("UPDATE jobs SET recipient='diferente@example.test' WHERE request_id=?",[$tampered]);
    $directSmtpWorker->tick();
    check($directSmtpApp->request($tampered)['status']==='failed','Impide cambiar el destinatario en la cola a otro distinto del formulario');
    $resendRequest=$app->createRequest($smtpData,'history-resend-test',true);
    $resendInitial=$app->historyResendInfo($resendRequest)['job'];
    rejects(fn()=>$app->resendHistory($resendRequest,(int)$resendInitial['id'],'resend-pending'),'No reenvía mientras el primer envío está pendiente');
    while($worker->tick()){}
    $resendInfo=$app->historyResendInfo($resendRequest);
    check($resendInfo['eligible'] && $resendInfo['remaining']===3 && $resendInfo['wait']>0,'Ofrece tres reenvíos con espera inicial');
    rejects(fn()=>$app->resendHistory($resendRequest,(int)$resendInitial['id'],'resend-too-soon'),'Servidor exige espera aunque se omita el botón');
    $past=date('Y-m-d H:i:s',time()-120);
    $db->run('UPDATE jobs SET sent_at=?,locked_at=?,created_at=? WHERE id=?',[$past,$past,$past,$resendInitial['id']]);
    $db->run("UPDATE packages SET status='withdrawn' WHERE id=?",[$resendInitial['package_id']]);
    rejects(fn()=>$app->resendHistory($resendRequest,(int)$resendInitial['id'],'resend-withdrawn'),'Reenvío rechaza paquete retirado');
    $db->run("UPDATE packages SET status='available' WHERE id=?",[$resendInitial['package_id']]);
    $resendFile=$app->packageFiles((int)$resendInitial['package_id'])[0]['path'];
    $originalBytes=file_get_contents($resendFile);
    file_put_contents($resendFile,'altered');
    clearstatcache();
    rejects(fn()=>$app->resendHistory($resendRequest,(int)$resendInitial['id'],'resend-tampered'),'Reenvío rechaza archivo alterado');
    file_put_contents($resendFile,$originalBytes);
    clearstatcache();
    // Existing deliveries were allowed to use an approximate date before exact-day search.
    $db->run('UPDATE requests SET approximate_date=? WHERE id=?',[date('Y-m-d',strtotime('-3 days')),$resendRequest]);
    foreach(['sent','failed','uncertain'] as $index=>$terminalState) {
        $previous=$app->historyResendInfo($resendRequest)['job'];
        $db->run('UPDATE jobs SET status=?,sent_at=?,locked_at=?,created_at=? WHERE id=?',[$terminalState,$past,$past,$past,$previous['id']]);
        $db->run('UPDATE requests SET status=? WHERE id=?',[$terminalState,$resendRequest]);
        $app->resendHistory($resendRequest,(int)$previous['id'],'resend-success-'.$index);
        $current=$app->historyResendInfo($resendRequest)['job'];
        check($current['status']==='queued' && $current['recipient']===$previous['recipient'] && $current['package_id']===$previous['package_id'] && $current['message_id']!==$previous['message_id'],'Reenvío desde '.$terminalState.' conserva paquete y correo, con mensaje nuevo');
        rejects(fn()=>$app->resendHistory($resendRequest,(int)$previous['id'],'resend-double-'.$index),'Doble clic no duplica reenvío '.$index);
        while($worker->tick()){}
        check($app->request($resendRequest)['status']==='simulated','Procesa reenvío completo '.$index);
        rejects(fn()=>$app->resendHistory($resendRequest,(int)$previous['id'],'resend-stale-'.$index),'Formulario anterior no reenvía otra vez '.$index);
    }
    $lastResend=$app->historyResendInfo($resendRequest);
    check($lastResend['remaining']===0,'Máximo de tres reenvíos por solicitud');
    rejects(fn()=>$app->resendHistory($resendRequest,(int)$lastResend['job']['id'],'resend-limit'),'Servidor bloquea el cuarto reenvío');
    check((int)$db->one("SELECT COUNT(*) n FROM jobs WHERE request_id=? AND kind='history'",[$resendRequest])['n']===4,'Conserva historial de entrega original y tres reenvíos');
    $suggestPatient=$db->insert('patients',['document_type'=>'CC','document_number'=>'6000000033','full_name'=>'Paciente Fechas','email'=>'']);
    [$recentEncounter,$recentPackage]=addEncounter($suggestPatient,-2);
    [$olderEncounter,$olderPackage]=addEncounter($suggestPatient,-90);
    addEncounter($suggestPatient,1);
    [$differentSpecialty]=addEncounter($suggestPatient,0,2);
    [,$withdrawnRecent]=addEncounter($suggestPatient,-1);
    $db->run("UPDATE packages SET status='withdrawn' WHERE id=?",[$withdrawnRecent]);
    [,,$missingRecentPaths]=addEncounter($suggestPatient,0);
    unlink($missingRecentPaths[0]);
    $suggestData=['document_type'=>'CC','document_number'=>'6000000033','full_name'=>'Paciente Fechas','approximate_date'=>date('Y-m-d',strtotime('-3 days')),'specialty_id'=>1,'email'=>'fechas@example.test'];
    $suggestRequest=$app->createRequest($suggestData,'suggest-date',true);
    check($app->request($suggestRequest)['status']==='no_matches','Fecha sin coincidencia exacta no envía automáticamente una consulta cercana');
    $suggestion=$app->recentSuggestion($suggestRequest);
    check((int)$suggestion['id']===$recentEncounter,'Sugiere la consulta más reciente de la especialidad, excluye futuro y paquetes retirados o incompletos');
    check((int)$db->one('SELECT COUNT(*) n FROM jobs WHERE request_id=?',[$suggestRequest])['n']===0,'Mostrar sugerencia no genera correos');
    check($app->recentSuggestion($mismatch)===null,'Nombre incorrecto no revela fechas de consultas');
    rejects(fn()=>$app->selectSuggestion($suggestRequest,$otherEncounter),'Sugerencia rechaza una atención de otro paciente');
    rejects(fn()=>$app->selectSuggestion($suggestRequest,$differentSpecialty),'Sugerencia no permite cambiar de especialidad por un ID manipulado');
    $db->run("UPDATE packages SET status='withdrawn' WHERE id=?",[$recentPackage]);
    rejects(fn()=>$app->selectSuggestion($suggestRequest,$recentEncounter),'Revalida disponibilidad al elegir la fecha sugerida');
    check((int)$app->recentSuggestion($suggestRequest)['id']===$olderEncounter,'Puede recomendar la última historia disponible fuera del rango anterior de treinta días');
    $db->run("UPDATE packages SET status='available' WHERE id=?",[$recentPackage]);
    $app->selectSuggestion($suggestRequest,$recentEncounter);
    $suggestedJob=$db->one("SELECT * FROM jobs WHERE request_id=? AND kind='history'",[$suggestRequest]);
    check($app->request($suggestRequest)['approximate_date']===date('Y-m-d',strtotime('-2 days')) && (int)$suggestedJob['package_id']===$recentPackage && $suggestedJob['recipient']==='fechas@example.test','Elegir sugerencia actualiza fecha y encola exclusivamente la consulta elegida al correo original');
    rejects(fn()=>$app->selectSuggestion($suggestRequest,$recentEncounter),'Doble clic en sugerencia no duplica el envío');
    check((int)$db->one('SELECT COUNT(*) n FROM jobs WHERE request_id=?',[$suggestRequest])['n']===1,'Sugerencia confirmada tiene una sola entrega');
    $exactRequest=$app->createRequest(array_replace($suggestData,['approximate_date'=>date('Y-m-d',strtotime('-2 days'))]),'exact-date',true);
    check($app->request($exactRequest)['status']==='queued' && $app->recentSuggestion($exactRequest)===null,'Coincidencia exacta mantiene entrega automática sin sugerencias');
    $db->run("UPDATE packages SET status='withdrawn' WHERE id IN (?,?)",[$recentPackage,$olderPackage]);
    $emptySuggestion=$app->createRequest($suggestData,'empty-suggestion',true);
    check($app->recentSuggestion($emptySuggestion)===null,'Sin historias disponibles de la especialidad no inventa una fecha');
    $anySpecialty=$app->createRequest(array_replace($suggestData,['specialty_id'=>0]),'any-specialty',true);
    check((int)$app->recentSuggestion($anySpecialty)['id']===$differentSpecialty,'No recuerdo la especialidad permite sugerir la última consulta entre especialidades');
    check($app->filters(['date_unknown'=>'1','approximate_date'=>'invalid','specialty_id'=>1],true)[0]===null,'No recuerdo la fecha omite incluso una fecha residual inválida');
    rejects(fn()=>$app->filters(['approximate_date'=>''],true),'Fecha vacía sin marcar la opción sigue siendo inválida');
    rejects(fn()=>$app->filters(['date_unknown'=>'1']),'Flujo histórico sigue requiriendo fecha');
    rejects(fn()=>$app->filters(['date_unknown'=>'1','specialty_id'=>999999],true),'Fecha desconocida mantiene validación de especialidad');
    $unknownDatePatient=$db->insert('patients',['document_type'=>'CC','document_number'=>'6000000044','full_name'=>'Paciente Sin Fecha','email'=>'']);
    [$todayEncounter,$todayPackage]=addEncounter($unknownDatePatient);
    addEncounter($unknownDatePatient,-60);
    $unknownDateData=['document_type'=>'CC','document_number'=>'6000000044','full_name'=>'Paciente Sin Fecha','date_unknown'=>'1','specialty_id'=>1,'email'=>'sinfecha@example.test'];
    $unknownDateRequest=$app->createRequest($unknownDateData,'unknown-date',true);
    check($app->request($unknownDateRequest)['approximate_date']===null,'Guarda ausencia de fecha sin inventar un día');
    check((int)$app->recentSuggestion($unknownDateRequest)['id']===$todayEncounter,'Sin fecha recomienda la consulta más reciente incluso si es hoy');
    check((int)$db->one('SELECT COUNT(*) n FROM jobs WHERE request_id=?',[$unknownDateRequest])['n']===0,'Sin fecha espera elección del paciente antes de enviar');
    rejects(fn()=>$app->confirm($unknownDateRequest,$todayEncounter),'No permite saltarse la selección de la fecha recomendada');
    $app->selectSuggestion($unknownDateRequest,$todayEncounter);
    $unknownDateJob=$db->one("SELECT * FROM jobs WHERE request_id=? AND kind='history'",[$unknownDateRequest]);
    check($app->request($unknownDateRequest)['approximate_date']===date('Y-m-d') && $unknownDateJob['recipient']==='sinfecha@example.test' && (int)$unknownDateJob['package_id']===$todayPackage,'Al elegir completa fecha real y encola paquete correcto');
    $unknownDateWrong=$app->createRequest(array_replace($unknownDateData,['full_name'=>'Otro nombre']),'unknown-date-wrong-name',true);
    check($app->recentSuggestion($unknownDateWrong)===null,'Fecha desconocida no muestra consultas cuando no coincide el paciente');
    $unknownDateEmpty=$app->createRequest(array_replace($unknownDateData,['specialty_id'=>2]),'unknown-date-empty',true);
    check($app->recentSuggestion($unknownDateEmpty)===null && (int)$db->one('SELECT COUNT(*) n FROM jobs WHERE request_id=?',[$unknownDateEmpty])['n']===0,'Sin consultas de esa especialidad no inventa fecha ni correo');
    $adminView=new App\AdminDeliveries($db);
    $adminByReference=$adminView->search($app->request($resendRequest)['reference']);
    check($adminByReference['total']===1 && (int)$adminByReference['rows'][0]['deliveries']===4,'Admin busca radicado y agrupa envío original con tres reenvíos');
    $adminByDocument=$adminView->search('6000000044');
    check($adminByDocument['total']===3,'Admin encuentra documento incluso en solicitud sin coincidencia de nombre');
    check($adminView->search('Paciente Sin Fecha')['total']===2,'Admin busca por nombre del paciente');
    check($adminView->search("' OR 1=1 --")['total']===0 && $adminView->search('%')['total']===0,'Buscador usa parámetros y trata comodines como texto literal');
    $adminAll=$adminView->search('',9999);
    check($adminAll['page']===$adminAll['pages'] && $adminAll['pages']>1 && count($adminAll['rows'])<=20,'Admin pagina todo el historial sin truncarlo a recientes');
    $adminDetail=$adminView->detail($resendRequest);
    check(count($adminDetail['deliveries'])===4 && count($adminDetail['deliveries'][0]['files'])===2,'Ojo muestra todos los envíos y los PDF del paquete');
    check(!array_key_exists('encrypted_payload',$adminDetail['deliveries'][0]),'Detalle de envíos no expone códigos cifrados');
    check($adminView->detail($unknown)['deliveries']===[],'Detalle explica solicitud sin envío generado');
    check($adminView->detail(999999999)===null,'Detalle inexistente no devuelve otra solicitud');
    // Older requests did not retain the claimed document; matched patient remains searchable.
    $db->run('UPDATE requests SET claimed_document_number=NULL,claimed_document_type=NULL WHERE id=?',[$resendRequest]);
    check(in_array($resendRequest,array_map('intval',array_column($adminView->search('6000000022')['rows'],'id')),true),'Admin conserva búsqueda por documento de solicitudes antiguas vinculadas');
    $bulk=new App\BulkImport($app);
    $bulkSources=[];
    foreach([['7000000011','BULKA001','NOTA'],['7000000011','BULKA001','ANEXO'],['7000000022','BULKB001','NOTA'],['7000000011','BULKA002','OTRA ATENCION']] as $i=>$fixture){
        $path=$config['storage_path'].'/histories/bulk-source-'.$i.'.pdf';
        file_put_contents($path,testPdf(...$fixture));
        $bulkSources[]=['path'=>$path,'name'=>'lote-'.$i.'.pdf'];
    }
    $bulkReport=$bulk->import($bulkSources);
    check($bulkReport['saved']===3 && $bulkReport['failed']===0,'Carga masiva separa pacientes y distintas atenciones del mismo paciente');
    check(count($app->packageFiles($bulkReport['results'][0]['package_id']))===2,'Carga masiva agrupa nota y anexo del mismo ingreso');
    $bulkAgain=$bulk->import(array_reverse($bulkSources));
    check($bulkAgain['reused']===3 && $bulkAgain['saved']===0,'Repetir lote en distinto orden no duplica paquetes');
    $bulkDuplicate=$bulk->import([$bulkSources[0],$bulkSources[1],$bulkSources[0]]);
    check($bulkDuplicate['reused']===1,'PDF repetido dentro del lote se deduplica');
    $badBulkPath=$config['storage_path'].'/histories/bulk-invalid.pdf';file_put_contents($badBulkPath,'not a PDF');
    $newBulkPath=$config['storage_path'].'/histories/bulk-new.pdf';file_put_contents($newBulkPath,testPdf('7000000033','BULKC001'));
    $badReport=$bulk->import([['path'=>$newBulkPath,'name'=>'nueva.pdf'],['path'=>$badBulkPath,'name'=>'ilegible.pdf']]);
    check($badReport['saved']===0 && $badReport['failed']===1 && $badReport['blocked']===1,'Un PDF no identificable bloquea publicación del lote completo');
    check($db->one("SELECT id FROM patients WHERE document_number='7000000033'")===null,'Lote bloqueado no deja pacientes ni historias parciales');
    rejects(fn()=>$bulk->import([]),'Carga masiva rechaza lote vacío');
    rejects(fn()=>$bulk->import(array_fill(0,21,$bulkSources[0])),'Carga masiva impone límite de archivos en servidor');
    rejects(fn()=>$bulk->receive(['complete'=>'0'],[]),'Carga masiva exige confirmar documentos completos');
    rejects(fn()=>$bulk->receive(['complete'=>'1','expected_files'=>2],[['error'=>UPLOAD_ERR_OK,'tmp_name'=>$newBulkPath,'name'=>'nueva.pdf']]),'Detecta recepción truncada antes de importar');
    rejects(fn()=>$bulk->receive(['complete'=>'1','expected_files'=>1],[['error'=>UPLOAD_ERR_OK,'tmp_name'=>$newBulkPath,'name'=>'nueva.pdf']]),'HTTP masivo no acepta rutas locales en lugar de cargas PHP');
    $conflictPath=$config['storage_path'].'/histories/bulk-conflict.pdf';
    file_put_contents($conflictPath,str_replace('Paciente ficticio','Paciente distinto',testPdf('7000000011','BULKA001','CONFLICTO')));
    $conflictReport=$bulk->import([$bulkSources[0],['path'=>$conflictPath,'name'=>'contradictorio.pdf'],['path'=>$newBulkPath,'name'=>'valido.pdf']]);
    check($conflictReport['failed']===1 && $conflictReport['saved']===1,'Conflicto en una atención no mezcla datos ni impide guardar otro grupo válido');
    check($adminView->search($app->request($direct)['reference'],1,true)['total']===0,'Historial excluye entregas simuladas');
    check($adminView->search($app->request($unknownDateRequest)['reference'],1,true)['total']===0,'Historial excluye solicitudes todavía en cola');
    $firstAccepted=$app->now();
    $db->run("UPDATE jobs SET status='sent',sent_at=? WHERE id=?",[$firstAccepted,$unknownDateJob['id']]);
    $db->run("UPDATE requests SET status='sent' WHERE id=?",[$unknownDateRequest]);
    $history=$adminView->search($app->request($unknownDateRequest)['reference'],1,true);
    check($history['total']===1 && $history['rows'][0]['closed_at']===$firstAccepted,'Envío validado entra automáticamente al historial con fecha de cierre');
    check($adminView->search('6000000044',1,true)['total']===1,'Historial conserva búsqueda por documento');
    check($adminView->search('Paciente Sin Fecha',1,true)['total']===1,'Historial conserva búsqueda por nombre');
    $later=$db->insert('jobs',['request_id'=>$unknownDateRequest,'package_id'=>$todayPackage,'kind'=>'history','recipient'=>'sinfecha@example.test','status'=>'failed','available_at'=>$app->now(),'created_at'=>$app->now(),'message_id'=>'<history-test@example.test>','dedupe_key'=>'history-test-failed']);
    $db->run("UPDATE requests SET status='failed' WHERE id=?",[$unknownDateRequest]);
    $history=$adminView->search($app->request($unknownDateRequest)['reference'],1,true);
    check($history['total']===1 && $history['rows'][0]['closed_at']===$firstAccepted && $history['rows'][0]['delivery_status']==='failed','Reenvío fallido no borra el cierre anterior ni oculta su estado actual');
    $db->run("UPDATE jobs SET status='sent',sent_at=? WHERE id=?",[date('Y-m-d H:i:s',time()+60),$later]);
    check($adminView->search($app->request($unknownDateRequest)['reference'],1,true)['total']===1,'Varios envíos exitosos no duplican el radicado en historial');
    $db->run('UPDATE requests SET matched_at=NULL WHERE id=?',[$unknownDateRequest]);
    check($adminView->search($app->request($unknownDateRequest)['reference'],1,true)['total']===0,'Historial requiere constancia de validación además de correo enviado');
    $caseAdmin=$db->insert('admins',['email'=>'case-admin@example.test','name'=>'Admin de prueba','password_hash'=>password_hash('synthetic-password',PASSWORD_DEFAULT)]);
    rejects(fn()=>$adminView->reopen($unknownDateRequest,$caseAdmin,$later),'No reabre un caso sin validación');
    $db->run('UPDATE requests SET matched_at=? WHERE id=?',[$app->now(),$unknownDateRequest]);
    rejects(fn()=>$adminView->reopen($unknownDateRequest,999999999,$later),'Reapertura exige administrador activo');
    rejects(fn()=>$adminView->reopen($unknownDateRequest,$caseAdmin,(int)$unknownDateJob['id']),'Formulario antiguo no reabre un envío diferente');
    $db->run("UPDATE jobs SET status='retry' WHERE id=?",[$later]);
    rejects(fn()=>$adminView->reopen($unknownDateRequest,$caseAdmin,$later),'No reabre mientras existe un envío en proceso');
    $db->run("UPDATE jobs SET status='failed' WHERE id=?",[$later]);
    $beforeJobs=$db->all('SELECT * FROM jobs WHERE request_id=? ORDER BY id',[$unknownDateRequest]);
    $adminView->reopen($unknownDateRequest,$caseAdmin,$later);
    $reopened=$adminView->detail($unknownDateRequest)['request'];
    check((int)$reopened['case_pending']===1 && (int)$reopened['case_reopened_by']===$caseAdmin && $reopened['case_reopened_at']!==null,'Reabrir registra pendiente, fecha y administrador');
    check($adminView->search($reopened['reference'],1,true)['total']===0,'Caso reabierto sale del historial de cerrados');
    check((int)$adminView->search('')['rows'][0]['id']===$unknownDateRequest,'Caso reabierto aparece primero en Solicitudes y envíos');
    check($beforeJobs===$db->all('SELECT * FROM jobs WHERE request_id=? ORDER BY id',[$unknownDateRequest]),'Reabrir no crea correos ni modifica envíos anteriores');
    check($db->one("SELECT result FROM events WHERE request_id=? AND action='case_reopened'",[$unknownDateRequest])['result']==='admin_'.$caseAdmin,'Reapertura queda en auditoría');
    rejects(fn()=>$adminView->reopen($unknownDateRequest,$caseAdmin,$later),'Doble confirmación no reabre ni duplica auditoría');
    $newSent=$db->insert('jobs',['request_id'=>$unknownDateRequest,'package_id'=>$todayPackage,'kind'=>'history','recipient'=>'sinfecha@example.test','status'=>'simulated','sent_at'=>$app->now(),'available_at'=>$app->now(),'created_at'=>$app->now(),'message_id'=>'<reopened-test@example.test>','dedupe_key'=>'reopened-test']);
    check((int)$adminView->detail($unknownDateRequest)['request']['case_pending']===1,'Entrega simulada no cierra un caso reabierto');
    $db->run("UPDATE jobs SET status='failed' WHERE id=?",[$newSent]);
    check((int)$adminView->detail($unknownDateRequest)['request']['case_pending']===1,'Envío fallido conserva caso pendiente');
    $db->run("UPDATE jobs SET status='sent' WHERE id=?",[$newSent]);
    check((int)$adminView->detail($unknownDateRequest)['request']['case_pending']===0 && $adminView->search($reopened['reference'],1,true)['total']===1,'Nuevo envío real cierra el caso incluso en el mismo segundo de reapertura');
    rejects(fn()=>$adminView->reopen($unknownDateRequest,$caseAdmin,$later),'Confirmación obsoleta no reabre un caso cerrado de nuevo');
    $adminView->reopen($unknownDateRequest,$caseAdmin,$newSent);
    check((int)$adminView->detail($unknownDateRequest)['request']['case_pending']===1 && (int)$db->one("SELECT COUNT(*) n FROM events WHERE request_id=? AND action='case_reopened'",[$unknownDateRequest])['n']===2,'Permite un nuevo ciclo de reapertura con auditoría independiente');
    [$targetRequest]=freshRequest();
    [$untouchedRequest]=freshRequest();
    $targetJob=(int)$db->one("SELECT id FROM jobs WHERE request_id=? AND kind='otp'",[$targetRequest])['id'];
    $db->run("UPDATE jobs SET status='sending',locked_at=? WHERE request_id=?",[date('Y-m-d H:i:s',time()-600),$untouchedRequest]);
    $unrelatedBefore=$db->all('SELECT * FROM jobs WHERE id<>? ORDER BY id',[$targetJob]);
    check($worker->tick($targetJob) && $db->one('SELECT status FROM jobs WHERE id=?',[$targetJob])['status']==='simulated','Procesador individual completa únicamente el trabajo seleccionado');
    check($unrelatedBefore===$db->all('SELECT * FROM jobs WHERE id<>? ORDER BY id',[$targetJob]),'Procesador individual no toca otros trabajos pendientes ni abandonados');
    check(!$worker->tick($targetJob) && !$worker->tick(999999999),'Procesador individual no repite enviados ni selecciona otro si no existe');
    echo "\nPASS: $checks comprobaciones. Sin envíos externos.\n";
} finally {
    // Only the randomly named database created by this test process is dropped.
    if (!preg_match('/^citaya_test_[a-f0-9]{10}$/',$databaseName)) throw new RuntimeException('Invalid test database name');
    $server->exec("DROP DATABASE `$databaseName`");
    foreach (['histories','outbox'] as $dir) { foreach(glob($config['storage_path'].'/'.$dir.'/*') as $file) unlink($file); rmdir($config['storage_path'].'/'.$dir); }
    rmdir($config['storage_path']);
}
