<div class="admin-heading"><div><span class="eyebrow">ACCESO INTERNO</span><h1>Gestión de historias clínicas</h1><p class="muted">Administra los documentos y consulta el seguimiento de sus envíos.</p></div><form method="post"><?= csrf() ?><input type="hidden" name="action" value="logout"><button class="button secondary">Cerrar sesión</button></form></div>
<nav class="tabs"><a class="<?= $page === 'admin' ? 'selected' : '' ?>" href="?page=admin">Repositorio</a><a class="<?= ($page === 'deliveries' || ($page === 'delivery' && ($_GET['from'] ?? '') !== 'history')) ? 'selected' : '' ?>" href="?page=deliveries">Solicitudes y envíos</a><a class="<?= ($page === 'history' || ($page === 'delivery' && ($_GET['from'] ?? '') === 'history')) ? 'selected' : '' ?>" href="?page=history">Historial de enviadas</a><a class="<?= $page === 'inbox' ? 'selected' : '' ?>" href="?page=inbox">Bandeja local</a></nav>
<?php if ($page === 'delivery'): require __DIR__ . '/delivery.php'; ?>
<?php elseif (in_array($page, ['deliveries','history'], true)): require __DIR__ . '/deliveries.php'; ?>
<?php elseif ($page === 'inbox'): ?>
<section class="card"><h2>Correos de simulación</h2><p class="muted">Estos mensajes se generaron con PHPMailer y se guardaron localmente. No se enviaron al destinatario externo.</p>
<?php if ($app->config['mail_transport'] !== 'local'): ?><div class="notice"><p>La bandeja local está desactivada porque el transporte configurado es SMTP.</p></div>
<?php else: $messages = $app->db->all("SELECT j.*,r.reference FROM jobs j JOIN requests r ON r.id=j.request_id WHERE j.status='simulated' ORDER BY j.id DESC LIMIT 30"); ?>
<?php if (!$messages): ?><div class="empty-state">Aún no hay correos. Crea una solicitud y mantén el procesador de cola en ejecución.</div><?php endif ?>
<?php foreach ($messages as $message): $mailPath = $app->config['storage_path'] . '/outbox/' . $message['id'] . '.eml'; $code = null;
if ($message['kind'] === 'otp' && is_file($mailPath)) { preg_match('/Tu código de verificación es: ([0-9]{6})/u', quoted_printable_decode(file_get_contents($mailPath)), $codeMatch); $code = $codeMatch[1] ?? null; }
?><article class="mail-item"><div class="mail-top"><span class="pill"><?= $message['kind'] === 'otp' ? 'VERIFICACIÓN' : 'HISTORIA COMPLETA' ?></span><small><?= h($message['sent_at']) ?></small></div><h3><?= h($message['reference']) ?></h3><p class="muted">Para: <?= h($message['recipient']) ?></p><?php if ($code): ?><p>Código de prueba: <strong class="mail-code"><?= h($code) ?></strong></p><small>Puede haber vencido o haber sido reemplazado por un código más reciente.</small><?php else: ?><p>Mensaje preparado con los documentos del paquete solicitado.</p><?php endif ?><a class="back-link" href="?page=mail&amp;id=<?= $message['id'] ?>">Descargar correo .eml →</a></article><?php endforeach ?>
<?php endif ?></section>
<?php else:
$counts = [
    'Pacientes' => $app->db->one('SELECT COUNT(*) n FROM patients')['n'],
    'Atenciones' => $app->db->one('SELECT COUNT(*) n FROM encounters')['n'],
    'Paquetes disponibles' => $app->db->one("SELECT COUNT(*) n FROM packages WHERE status='available'")['n'],
    'Solicitudes' => $app->db->one('SELECT COUNT(*) n FROM requests')['n'],
]; ?>
<div class="stats"><?php foreach ($counts as $label => $value): ?><div class="stat"><strong><?= h($value) ?></strong><span><?= h($label) ?></span></div><?php endforeach ?></div>
<?php require __DIR__ . '/upload-center.php'; ?>
<section class="card spaced"><h2>Historias registradas</h2><div class="table-wrap"><table class="responsive-table" role="table"><thead role="rowgroup"><tr role="row"><th scope="col" role="columnheader">Paciente</th><th scope="col" role="columnheader">Atención</th><th scope="col" role="columnheader">Paquete</th><th scope="col" role="columnheader">Estado</th><th scope="col" role="columnheader">Acción</th></tr></thead><tbody role="rowgroup">
<?php $packages = $app->db->all('SELECT p.*,e.attended_at,e.admission,s.name specialty,pa.full_name,pa.document_type,pa.document_number,(SELECT COUNT(*) FROM clinical_files f WHERE f.package_id=p.id) files,(SELECT SUM(f.page_count) FROM clinical_files f WHERE f.package_id=p.id) pages FROM packages p JOIN encounters e ON e.id=p.encounter_id JOIN patients pa ON pa.id=e.patient_id JOIN specialties s ON s.id=e.specialty_id ORDER BY p.id DESC LIMIT 50'); ?>
<?php foreach ($packages as $package): ?><tr role="row"><td role="cell" data-label="Paciente"><strong><?= h($package['full_name']) ?></strong><small><?= h($package['document_type'] . ' ' . $package['document_number']) ?></small></td><td role="cell" data-label="Atención"><?= h($package['specialty']) ?><small><?= date('d/m/Y', strtotime($package['attended_at'])) ?> · <?= h($package['admission']) ?></small></td><td role="cell" data-label="Paquete"><?= $package['files'] ?> PDF<?= $package['pages'] ? ' · ' . (int)$package['pages'] . ' páginas' : '' ?> · v<?= $package['version'] ?></td><td role="cell" data-label="Estado"><span class="pill"><?= $package['status'] === 'available' ? 'Disponible' : 'Retirado / incompleto' ?></span></td><td role="cell" data-label="Acción"><?php if ($package['status'] === 'available'): ?><form method="post" data-confirm="Retirar este paquete impedirá nuevas entregas. Los correos ya enviados no se pueden recuperar."><?= csrf() ?><input type="hidden" name="action" value="withdraw"><input type="hidden" name="package_id" value="<?= $package['id'] ?>"><button class="text-button danger">Retirar</button></form><?php endif ?></td></tr><?php endforeach ?>
</tbody></table></div></section>
<?php endif ?>
