<div class="table-wrap"><table class="history-table responsive-table" role="table"><thead role="rowgroup"><tr role="row"><th scope="col" role="columnheader">Radicado / fecha</th><th scope="col" role="columnheader">Paciente</th><th scope="col" role="columnheader">Atención médica</th><th scope="col" role="columnheader">Tipo de requerimiento</th><th scope="col" role="columnheader">Gestión</th><th scope="col" role="columnheader">Estado</th><th scope="col" role="columnheader">Acciones</th></tr></thead><tbody role="rowgroup">
<?php foreach ($deliverySearch['rows'] as $row): ?><tr role="row">
<td role="cell" data-label="Radicado / fecha"><strong class="history-reference"><?= h($row['reference']) ?></strong><small><?= h(date('d/m/Y, h:i a',strtotime($row['created_at']))) ?></small></td>
<td role="cell" data-label="Paciente"><strong><?= h($row['claimed_name']) ?></strong><small><?= $row['document_number'] ? h($row['document_type'].' '.$row['document_number']) : 'Documento no conservado' ?></small></td>
<td role="cell" data-label="Atención médica"><span class="history-date"><?= $row['attended_at'] ? h(date('d/m/Y',strtotime($row['attended_at']))) : 'Sin fecha registrada' ?></span><small><?= h($row['specialty'] ?? '—') ?></small><small>Canal: Web</small></td>
<td role="cell" data-label="Tipo de requerimiento"><span class="history-type">HISTORIA CLÍNICA</span></td>
<td role="cell" data-label="Gestión"><span class="history-closed">✓ CERRADO</span><small><?= h(date('d/m/Y, h:i a',strtotime($row['closed_at']))) ?></small></td>
<td role="cell" data-label="Estado"><span class="history-approved" title="Validada automáticamente y enviada por correo">✓ APROBADO</span><small>Envío aceptado</small><?php if ($row['status'] !== 'sent'): ?><small>Último intento: <?= h($labels[$row['status']] ?? $row['status']) ?></small><?php endif ?></td>
<td role="cell" data-label="Acciones"><div class="history-actions"><button type="button" class="button reopen-button" data-reopen-case data-request-id="<?= (int)$row['id'] ?>" data-job-id="<?= (int)$row['last_job_id'] ?>" data-reference="<?= h($row['reference']) ?>" aria-label="Reabrir caso <?= h($row['reference']) ?>" title="Reabrir caso" aria-haspopup="dialog" aria-controls="reopen-modal" disabled><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M12 2v10M6 5a9 9 0 1 0 12 0"/></svg></button><a class="button secondary eye-button" data-delivery-modal aria-haspopup="dialog" aria-controls="delivery-modal" href="?page=delivery&amp;id=<?= (int)$row['id'] ?>&amp;from=history&amp;q=<?= rawurlencode($deliverySearch['query']) ?>&amp;p=<?= (int)$deliverySearch['page'] ?>" aria-label="Ver envío de <?= h($row['reference']) ?>" title="Ver detalle del envío"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></svg></a></div></td>
</tr><?php endforeach ?></tbody></table></div>
