<?php $isHistory=!empty($deliverySearch['history']); $listPage=$isHistory?'history':'deliveries'; ?>
<section class="card spaced" id="deliveries"><h2><?= $isHistory ? 'Historial de historias enviadas' : 'Solicitudes y envíos' ?></h2><p class="muted"><?= $isHistory ? 'Solicitudes aprobadas automáticamente y con envío aceptado por el servidor de correo. Los casos reabiertos pasan a Solicitudes y envíos hasta completar un nuevo envío.' : 'Busca al paciente y consulta el seguimiento de su historia clínica.' ?></p>
<form method="get" class="delivery-search"><input type="hidden" name="page" value="<?= $listPage ?>"><label for="delivery-query">Nombre, radicado o número de documento<input id="delivery-query" type="search" name="q" maxlength="160" placeholder="Ej.: nombre completo, HC-… o cédula" value="<?= h($deliverySearch['query']) ?>"></label><button class="button primary" type="submit">Buscar</button><?php if ($deliverySearch['query'] !== ''): ?><a class="button secondary" href="?page=<?= $listPage ?>">Limpiar</a><?php endif ?></form>
<p class="muted" role="status"><?= (int)$deliverySearch['total'] ?> solicitud(es)<?= $deliverySearch['query'] !== '' ? ' para «' . h($deliverySearch['query']) . '»' : '' ?>.</p>
<?php if (!$deliverySearch['rows']): ?><div class="empty-state"><?= $isHistory ? 'No hay historias enviadas que coincidan con la búsqueda. Las entregas simuladas o fallidas no aparecen en este historial.' : 'No se encontraron solicitudes con esos datos. Prueba con parte del nombre, el radicado o el documento.' ?></div>
<?php else: ?>
<?php if ($isHistory): require __DIR__ . '/delivery-history-rows.php'; else: ?><div class="table-wrap"><table class="responsive-table" role="table"><thead role="rowgroup"><tr role="row"><th scope="col" role="columnheader">Paciente</th><th scope="col" role="columnheader">Radicado / fecha</th><th scope="col" role="columnheader">Correo de entrega</th><th scope="col" role="columnheader">Estado</th><th scope="col" role="columnheader">Envíos</th><th scope="col" role="columnheader">Ver</th></tr></thead><tbody role="rowgroup">
<?php foreach ($deliverySearch['rows'] as $row): ?><tr role="row"><td role="cell" data-label="Paciente"><strong><?= h($row['claimed_name']) ?></strong><small><?= $row['document_number'] ? h($row['document_type'].' '.$row['document_number']) : 'Documento no conservado en esta solicitud antigua' ?></small></td><td role="cell" data-label="Radicado / fecha"><?= h($row['reference']) ?><small><?= h($row['created_at']) ?></small></td><td role="cell" data-label="Correo de entrega" class="delivery-email"><?= h($row['contact_email'] ?? '—') ?></td><td role="cell" data-label="Estado"><?php if ($row['case_pending']): ?><span class="pill case-pending">Pendiente de gestión</span><small>Reabierto <?= h($row['case_reopened_at']) ?></small><?php endif ?><span class="pill"><?= h($labels[$row['status']] ?? $row['status']) ?></span><?php if ($row['last_error']): ?><small class="danger">Último envío con error</small><?php endif ?></td><td role="cell" data-label="Envíos"><?= (int)$row['deliveries'] ?></td><td role="cell" data-label="Ver"><a class="button secondary eye-button" data-delivery-modal aria-haspopup="dialog" aria-controls="delivery-modal" href="?page=delivery&amp;id=<?= (int)$row['id'] ?>&amp;q=<?= rawurlencode($deliverySearch['query']) ?>&amp;p=<?= (int)$deliverySearch['page'] ?>" aria-label="Ver envío de <?= h($row['reference']) ?>" title="Ver detalle del envío"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></svg></a></td></tr><?php endforeach ?>
</tbody></table></div><?php endif ?>
<nav class="delivery-pagination" aria-label="Páginas de solicitudes"><?php if ($deliverySearch['page']>1): ?><a class="button secondary" href="?page=<?= $listPage ?>&amp;q=<?= rawurlencode($deliverySearch['query']) ?>&amp;p=<?= $deliverySearch['page']-1 ?>">← Anterior</a><?php endif ?><span class="muted">Página <?= (int)$deliverySearch['page'] ?> de <?= (int)$deliverySearch['pages'] ?></span><?php if ($deliverySearch['page']<$deliverySearch['pages']): ?><a class="button secondary" href="?page=<?= $listPage ?>&amp;q=<?= rawurlencode($deliverySearch['query']) ?>&amp;p=<?= $deliverySearch['page']+1 ?>">Siguiente →</a><?php endif ?></nav>
<?php endif ?></section>
<dialog id="delivery-modal" class="delivery-modal" aria-labelledby="delivery-modal-title">
<div class="delivery-modal-header"><h2 id="delivery-modal-title">Detalle del envío</h2><button class="button secondary" type="button" data-close-delivery aria-label="Cerrar detalle del envío">Cerrar <span aria-hidden="true">×</span></button></div>
<div class="delivery-modal-content" data-delivery-content aria-live="polite"></div>
</dialog>
<?php if ($isHistory): ?>
<dialog id="reopen-modal" class="reopen-modal" aria-labelledby="reopen-title" aria-describedby="reopen-description">
<div class="reopen-icon" aria-hidden="true"><svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 2v10M6 5a9 9 0 1 0 12 0"/></svg></div>
<h2 id="reopen-title">Reabrir caso</h2><p id="reopen-description">¿Reabrir el caso <strong data-reopen-reference></strong> y volver a Pendiente?</p>
<form method="post"><?= csrf() ?><input type="hidden" name="action" value="reopen-case"><input type="hidden" name="request_id"><input type="hidden" name="expected_job_id"><div class="reopen-buttons"><button type="button" class="button secondary" data-cancel-reopen autofocus>Cancelar</button><button type="submit" class="button reopen-confirm">Confirmar</button></div></form>
</dialog>
<noscript><p class="muted">Activa JavaScript para abrir la confirmación de reapertura.</p></noscript>
<?php endif ?>
