<?php if (empty($deliveryModal)): ?><a class="back-link" href="?page=<?= ($_GET['from'] ?? '') === 'history' ? 'history' : 'deliveries' ?>&amp;q=<?= rawurlencode(mb_substr((string)($_GET['q'] ?? ''),0,160)) ?>&amp;p=<?= max(1,(int)($_GET['p'] ?? 1)) ?>">← Volver a los resultados</a><?php endif ?>
<?php if (!$deliveryDetail): ?><section class="card spaced"><h2>Solicitud no encontrada</h2><p class="muted">El radicado indicado no está disponible.</p></section>
<?php else: $record=$deliveryDetail['request']; ?>
<section class="card spaced"><span class="eyebrow">DETALLE DE LA SOLICITUD</span><h2 class="spaced"><?= h($record['reference']) ?></h2><span class="pill"><?= h($labels[$record['status']] ?? $record['status']) ?></span>
<?php if ($record['case_pending']): ?><div class="notice"><strong>Pendiente de gestión</strong><p>Caso reabierto el <?= h($record['case_reopened_at']) ?>. Los envíos anteriores se conservan.</p></div><?php endif ?>
<dl class="delivery-facts"><div><dt>Nombre declarado</dt><dd><?= h($record['claimed_name']) ?></dd></div><div><dt>Documento</dt><dd><?= $record['document_number'] ? h($record['document_type'].' '.$record['document_number']) : 'No conservado en esta solicitud antigua' ?></dd></div><div><dt>Correo solicitado</dt><dd><?= h($record['contact_email'] ?? '—') ?></dd></div><div><dt>Solicitud creada</dt><dd><?= h($record['created_at']) ?></dd></div><div><dt>Fecha indicada / elegida</dt><dd><?= $record['approximate_date'] ? h(date('d/m/Y',strtotime($record['approximate_date']))) : 'No recuerda la fecha' ?></dd></div><div><dt>Especialidad</dt><dd><?= h($record['specialty'] ?? 'No indicada') ?></dd></div><div><dt>Atención seleccionada</dt><dd><?= $record['attended_at'] ? h(date('d/m/Y H:i',strtotime($record['attended_at']))) : 'Sin selección' ?></dd></div><div><dt>Paciente localizado en los PDF</dt><dd><?= h($record['indexed_name'] ?? 'Sin coincidencia') ?></dd></div></dl></section>
<?php if (empty($deliveryModal)): ?>
<section class="card spaced"><h2>Historial de envíos y reenvíos</h2><p class="muted">«Correo enviado» indica que el servidor aceptó el mensaje; no confirma su recepción en la bandeja de entrada ni su lectura.</p>
<?php if (!$deliveryDetail['deliveries']): ?><div class="empty-state">Esta solicitud todavía no ha generado un envío de historia clínica.</div><?php endif ?>
<?php foreach ($deliveryDetail['deliveries'] as $index=>$delivery): ?>
<article class="mail-item"><div class="mail-top"><h3><?= $index===count($deliveryDetail['deliveries'])-1 ? 'Envío original' : 'Reenvío ' . (count($deliveryDetail['deliveries'])-$index-1) ?> · #<?= (int)$delivery['id'] ?></h3><span class="pill"><?= h($labels[$delivery['status']] ?? $delivery['status']) ?></span></div>
<dl class="delivery-facts"><div><dt>Destinatario de este envío</dt><dd><?= h($delivery['recipient']) ?></dd></div><div><dt>Intentos de procesamiento</dt><dd><?= (int)$delivery['attempts'] ?></dd></div><div><dt>Encolado</dt><dd><?= h($delivery['created_at']) ?></dd></div><div><dt><?= $delivery['status']==='simulated' ? 'Simulación preparada' : 'Aceptado por el servidor' ?></dt><dd><?= h($delivery['sent_at'] ?? 'Sin confirmación') ?></dd></div></dl>
<?php if ($delivery['last_error']): ?><div class="alert error"><strong>Motivo registrado:</strong> <?= h($delivery['last_error']) ?></div><?php endif ?>
<p class="muted"><strong>Asunto:</strong> Respuesta a tu solicitud <?= h($record['reference']) ?></p><h3>PDF asociados al envío</h3>
<?php if (!$delivery['files']): ?><p class="muted">No hay archivos asociados disponibles en el repositorio.</p><?php else: ?><ul class="delivery-files"><?php foreach ($delivery['files'] as $file): ?><li><?= h($file['original_name']) ?><small><?= $file['page_count'] ? (int)$file['page_count'].' páginas · ' : '' ?><?= h(number_format((int)$file['size_bytes']/1024,1,',','.')) ?> KB</small></li><?php endforeach ?></ul><?php endif ?>
<details><summary>Identificador técnico del mensaje</summary><p class="delivery-message-id"><?= h($delivery['message_id']) ?></p></details>
</article><?php endforeach ?></section>
<?php endif ?>
<?php endif ?>
